export { default as About } from './About/About'
export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as Hero } from './Hero/Hero'
export { default as Highlights } from './Highlights/Highlights'
export { default as Testimonials } from './Testimonials/Testimonials'