export { default as Homepage } from './Homepage/Homepage'
export { default as Login } from './Login/Login'
export { default as Menu } from './Menu/Menu'
export { default as OrderOnline } from './OrderOnline/OrderOnline'
export { Reservation } from './Reservation/Reservation'
export { default as About } from './About/About'